name: Archive Old Branches

on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ArchiveStaleBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
        
      - name: Filter and archive stale branches
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all branches
          gh api repos/${{ github.repository }}/branches | jq -r '.[].name' > branches.txt

          # Loop through branches
          while read branch; do
            # Skip main branch
            if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
              echo "Skipping main branch: $branch"
              continue
            fi

              echo "Non-default branch: $branch"
          done < branches.txt

